Add spring support to Java base image
dispatchframework/java-base-image pull request #4
Opened 2018-04-25 18:27 UTC by tenczar

Modifies the application entry point to start either a Spring or plain old Java version of the dispatch function handling server. Assumes that a user is using Spring if the BeanFactory can be found on the classpath. Create a FunctionExecutor interface that both servers rely on to do the heavy lifting. SpringFunctionServer was written to use Undertow's Servlet support. This is necessary to support "request" scoped beans in the future.

2018-05-01 19:18 UTC, imikushin requested changes
Pretty great overall! 
A few minor changes are needed though.

Also, one general comment about indentation: let's do 4 spaces (vs 1 tab) per indent for *.java and *.xml

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SpringFunctionServlet.java
> +			res.setContentType("application/json");
This should come before any content is written to the response body.

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SpringFunctionServlet.java
> +		return body;
`String body` variable is not needed as it's only usage is to be assigned the result of `sb.toString()` which is immediately returned.

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SpringFunctionServlet.java
> + * **********************************************************/
You probably want to either remove file header comments altogether or make them consistent. 

If you want to have them, please populate with the license header as in vmware/dispatch repo.

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SpringFunctionServlet.java
> + */
Empty Javadoc comment?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SpringFunctionServlet.java
> +		// TODO Auto-generated method stub
Doesn't look like a real TODO. Please remove or be specific: **what** exactly needs to be done, and **why** (if not obvious from **what**).

If a method is to remain empty (or populated with trivial auto-generated code), it is a good practice to leave a comment as to why, but that's not required.

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SpringFunctionServlet.java
> +		// TODO Auto-generated method stub
Same as above ^

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SpringFunctionServer.java
> + */
Empty Javadoc comment?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SpringFunctionServer.java
> + */
Empty package comment?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SimpleFunctionExecutor.java
> +	 */
(non-Javadoc)? 
Is this really needed?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SimpleFunctionExecutor.java
> + */
Empty Javadoc comment?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/SimpleFunctionExecutor.java
> + */
Empty package comment?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/Server.java
> + */
Empty Javadoc comment?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/Server.java
> + */
Empty package comment?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/HealthzServlet.java
> +	 */
(non-Javadoc)?
Is this really needed?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/HealthzServlet.java
> +	 */
(non-Javadoc)?
Is this really needed?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/HealthzServlet.java
> +	 */
(non-Javadoc)?
Is this really needed?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/HealthzServlet.java
> +	 */
(non-Javadoc)?
Is this really needed?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/HealthzServlet.java
> +	 */
(non-Javadoc)?
Is this really needed?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/HealthzServlet.java
> + */
Empty Javadoc comment?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/HealthzServlet.java
> + */
Empty package comment?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/Entrypoint.java
> +//		server.stop();
Please remove if this code is not needed.

2018-05-01 19:18 UTC, imikushin commented on Dockerfile
> +CMD java -cp target/classes:target/*:target/lib/* io.dispatchframework.javabaseimage.Entrypoint $(cat /tmp/package) $(cat /tmp/class)
Is `target/*` for the .jar files that end up in `target/`? Is `target/classes` still needed then?

2018-05-01 19:18 UTC, imikushin commented on function-server/src/main/java/io/dispatchframework/javabaseimage/Entrypoint.java
> +			Class.forName("org.springframework.beans.factory.BeanFactory");
What if Spring libraries are available because they are supplied by the _image_, but the _function_ doesn't really depend on Spring? (if there are no Inject or other Spring related annotations)

2018-05-01 22:37 UTC, tenczar commented on Dockerfile
> +CMD java -cp target/classes:target/*:target/lib/* io.dispatchframework.javabaseimage.Entrypoint $(cat /tmp/package) $(cat /tmp/class)
`target/*` is needed for the jar created by `mvn package`. Annoyingly this `-cp` flag does the same thing as package imports in java do. This `import java.util.*` only imports all of the classes directly under java.util. It does not include stuff imported using `import java.util.concurrent.*`

2018-05-02 16:23 UTC, imikushin commented on Dockerfile
> +CMD java -cp target/classes:target/*:target/lib/* io.dispatchframework.javabaseimage.Entrypoint $(cat /tmp/package) $(cat /tmp/class)
Is `target/classes` still needed?

2018-05-02 18:15 UTC, tenczar commented on Dockerfile
> +CMD java -cp target/classes:target/*:target/lib/* io.dispatchframework.javabaseimage.Entrypoint $(cat /tmp/package) $(cat /tmp/class)
yes, because the cp flag does not recursively add files in sub directories. It only loads class and jar files found at the directory that was passed to the flag.

2018-05-07 19:01 UTC, imikushin approved these changes

2018-05-07 19:02 UTC, merged